spring.application.name=gateway


spring.cors.url[0]=localhost:3000
spring.cors.url[1]=http://localhost:3000
spring.cors.url[2]=https://localhost:3000

spring.cloud.gateway.routes[0].id=login-service
spring.cloud.gateway.routes[0].uri=${LOGIN_URI}
spring.cloud.gateway.routes[0].predicates[0]=Path=/module2/v1/auth/**


spring.cloud.gateway.routes[1].id=module1-service
spring.cloud.gateway.routes[1].uri=${MODULE1_URI}
spring.cloud.gateway.routes[1].predicates[0]=Path=/pessoa/v1/** 