spring.application.name=gateway


spring.cloud.gateway.routes[0].id=login-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/module2/v1/auth/**

spring.cloud.gateway.routes[1].id=module1-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/pessoa/v1/**